export const SCAM_CATEGORIES = [
  "GDTG MMO",
  "Free Fire",
  "Liên Quân",
  "Roblox",
  "FC Online",
  "Valorant",
  "Zing Speed",
  "NRO",
  "Pr Story",
  "Nạp game",
  "Mua, gạch thẻ",
  "Dv.Google",
  "Dv.Tiktok",
  "Dv.Youtube",
  "Dv.Facebook",
  "Dv.Wechat",
  "Fanpage, group",
  "Paypal, payoner...",
  "Pubg Mobile",
  "Game Pass",
  "Tk Chat GPT - Canva Pro",
  "Cày thuê Game",
  "Mua bán tiền điện tử",
  "Rút ví trả sau",
  "Thiết kế, Code web",
  "Hosting, vps, domain, Proxy",
  "Thanh toán cước, vocher",
  "Tk Netflix, YouTube, Spotify…",
  "Thẻ playerduo, code steam, tinder..",
  "Chuyển tiền quốc tế",
  "Tài khoản, sim số đẹp",
];

export const BANK_LIST = [
  "Vietcombank",
  "Techcombank",
  "BIDV",
  "Agribank",
  "VietinBank",
  "MB Bank",
  "ACB",
  "Sacombank",
  "VPBank",
  "TPBank",
  "HDBank",
  "SHB",
  "VIB",
  "Eximbank",
  "OCB",
  "MSB",
  "PVcomBank",
  "BaoVietBank",
  "Saigonbank",
  "BacABank",
  "NamABank",
  "VietBank",
  "KienLongBank",
  "NCB",
  "OceanBank",
  "GPBank",
  "ABBank",
  "PG Bank",
  "DongABank",
  "VietCapitalBank",
];

export const API_ENDPOINTS = {
  ACCOUNT_REPORTS: "/api/account-reports",
  WEBSITE_REPORTS: "/api/website-reports",
  SEARCH: "/api/search",
  DASHBOARD: "/api/dashboard",
  INSURANCE_ADMINS: "/api/insurance-admins",
  COMMENTS: "/api/comments",
  UPLOAD: "/api/upload",
};
